### ISSUE TITLE
Cannot import model LSTM

### ISSUE THREAD

**Issue by alisonsin** [traja-team/traja#96]
When I run the code: from traja.models.predictive_models.lstm import LSTM. It says that No module named 'traja.models.predictive_models'
I'm wondering how I can go about it. Thanks!

**Comment by Saran-nns** [comment]
hi, thanks for reporting the issue. 

I installed the latest version `traja-0.2.8` in a new environment. 


```
>>> from traja.models.predictive_models.lstm import LSTM
>>> LSTM()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 10 required positional arguments: 'batch_size', 'num_future', 'hidden_size', 'num_layers', 'output_size', 'input_size', 'batch_first', 'dropout', 'reset_state', and 'bidirectional'
>>>
```

The import works both in a shell and in a virtual environment. 

In your case, I suspect you might be facing an environmental issue. Please make sure you call the package from the same python kernel and virtual env. Otherwise, the issue might be failure of `traja` installation for some reason, which could be related to its dependencies. If so please report the detailed bug with the `traja` version.

**Comment by Saran-nns** [comment]
@alisonsin  @justinshenk I close this issue as resolved. Please feel free to reopen it if there are any issues.
